#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
	CREATE ROLE j1 WITH CREATEDB;
	CREATE ROLE promotion WITH LOGIN;
	CREATE ROLE employees WITH LOGIN;
	CREATE ROLE welfare WITH LOGIN;
	CREATE ROLE general_affairs WITH LOGIN;
	CREATE ROLE j2 WITH CREATEDB;
	CREATE ROLE access WITH LOGIN;
	CREATE ROLE targeting WITH LOGIN;
	CREATE ROLE licenses WITH LOGIN;
	CREATE ROLE doc_mgt WITH LOGIN;
	CREATE ROLE licences WITH LOGIN;
	CREATE ROLE j3 WITH CREATEDB;
	CREATE ROLE ops WITH LOGIN;
	CREATE ROLE training WITH LOGIN;
	CREATE ROLE plan_24 WITH LOGIN;
	CREATE ROLE plan_48 WITH LOGIN;
	CREATE ROLE week_plan WITH LOGIN;
	CREATE ROLE options WITH LOGIN;
	CREATE ROLE j4 WITH CREATEDB;
	CREATE ROLE move WITH LOGIN;
	CREATE ROLE med WITH LOGIN;
	CREATE ROLE maint WITH LOGIN;
	CREATE ROLE supply WITH LOGIN;
	CREATE ROLE w_n_a WITH LOGIN;
	CREATE ROLE storage WITH LOGIN;
	CREATE ROLE j5 WITH CREATEDB;
	CREATE ROLE r_n_d WITH LOGIN;
	CREATE ROLE long_term_view WITH LOGIN;
	CREATE ROLE plan_3_years WITH LOGIN;
	CREATE ROLE plan_5_years WITH LOGIN;
	CREATE ROLE j35 WITH LOGIN;
	CREATE ROLE j6 WITH CREATEDB;
	CREATE ROLE helpdesk WITH LOGIN;
	CREATE ROLE doc_rules WITH LOGIN;
	CREATE ROLE com_plan WITH LOGIN;
	CREATE ROLE post_office WITH LOGIN;
	CREATE ROLE transmission WITH LOGIN;
	CREATE ROLE j7 WITH CREATEDB;
	CREATE ROLE plan_ow WITH LOGIN;
	CREATE ROLE international_relation WITH LOGIN;
	CREATE ROLE j8 WITH CREATEDB;
	CREATE ROLE procurement_office WITH LOGIN;
	CREATE ROLE plan_ad WITH LOGIN;

EOSQL

