#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
	CREATE ROLE j1_chief;
	GRANT       j1 TO j1_chief;
	ALTER ROLE  j1_chief WITH LOGIN PASSWORD 'user_chief_j1';
	CREATE ROLE j1_user_1;
	GRANT       promotion TO j1_user_1;
	ALTER ROLE  j1_user_1 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j1_user_2;
	GRANT       promotion TO j1_user_2;
	ALTER ROLE  j1_user_2 WITH LOGIN PASSWORD 'user_2';
	CREATE ROLE j1_user_3;
	GRANT       welfare TO j1_user_3;
	ALTER ROLE  j1_user_3 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j1_user_4;
	GRANT       general_affairs TO j1_user_4;
	ALTER ROLE  j1_user_4 WITH LOGIN PASSWORD 'user_2';
	CREATE ROLE j1_user_5;
	GRANT       general_affairs TO j1_user_5;
	ALTER ROLE  j1_user_5 WITH LOGIN PASSWORD 'user_2';
	CREATE ROLE j1_user_6;
	GRANT       general_affairs TO j1_user_6;
	ALTER ROLE  j1_user_6 WITH LOGIN PASSWORD 'user_2';
	CREATE ROLE j2_chief;
	GRANT       j2 TO j2_chief;
	ALTER ROLE  j2_chief WITH LOGIN PASSWORD 'qawsc';
	CREATE ROLE j2_user_1;
	GRANT       access TO j2_user_1;
	ALTER ROLE  j2_user_1 WITH LOGIN PASSWORD 'qawsa';
	CREATE ROLE j2_user_2;
	GRANT       access TO j2_user_2;
	ALTER ROLE  j2_user_2 WITH LOGIN PASSWORD 'qawsa';
	CREATE ROLE j2_user_3;
	GRANT       targeting TO j2_user_3;
	ALTER ROLE  j2_user_3 WITH LOGIN PASSWORD 'qawst';
	CREATE ROLE j2_user_4;
	GRANT       licenses TO j2_user_4;
	ALTER ROLE  j2_user_4 WITH LOGIN PASSWORD 'qawsl';
	CREATE ROLE j2_user_5;
	GRANT       doc_mgt TO j2_user_5;
	ALTER ROLE  j2_user_5 WITH LOGIN PASSWORD 'qawsd';
	CREATE ROLE j2_user_6;
	GRANT       doc_mgt TO j2_user_6;
	ALTER ROLE  j2_user_6 WITH LOGIN PASSWORD 'qawsd';
	CREATE ROLE j3_chief;
	GRANT       j3 TO j3_chief;
	ALTER ROLE  j3_chief WITH LOGIN PASSWORD 'user_chief_j3';
	CREATE ROLE j3_user_1;
	GRANT       ops TO j3_user_1;
	ALTER ROLE  j3_user_1 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j3_user_2;
	GRANT       training TO j3_user_2;
	ALTER ROLE  j3_user_2 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j3_user_3;
	GRANT       plan_24 TO j3_user_3;
	ALTER ROLE  j3_user_3 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j3_user_4;
	GRANT       plan_48 TO j3_user_4;
	ALTER ROLE  j3_user_4 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j3_user_5;
	GRANT       week_plan TO j3_user_5;
	ALTER ROLE  j3_user_5 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j3_user_6;
	GRANT       options TO j3_user_6;
	ALTER ROLE  j3_user_6 WITH LOGIN PASSWORD 'user_2';
	CREATE ROLE j4_chief;
	GRANT       j4 TO j4_chief;
	ALTER ROLE  j4_chief WITH LOGIN PASSWORD 'user_chief_j4';
	CREATE ROLE j4_user_1;
	GRANT       move TO j4_user_1;
	ALTER ROLE  j4_user_1 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j4_user_2;
	GRANT       med TO j4_user_2;
	ALTER ROLE  j4_user_2 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j4_user_3;
	GRANT       maint TO j4_user_3;
	ALTER ROLE  j4_user_3 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j4_user_4;
	GRANT       supply TO j4_user_4;
	ALTER ROLE  j4_user_4 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j4_user_5;
	GRANT       w_n_a TO j4_user_5;
	ALTER ROLE  j4_user_5 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j4_user_6;
	GRANT       storage TO j4_user_6;
	ALTER ROLE  j4_user_6 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j5_chief;
	GRANT       j5 TO j5_chief;
	ALTER ROLE  j5_chief WITH LOGIN PASSWORD 'user_chief_j5';
	CREATE ROLE j5_user_1;
	GRANT       r_n_d TO j5_user_1;
	ALTER ROLE  j5_user_1 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j5_user_2;
	GRANT       long_term_view TO j5_user_2;
	ALTER ROLE  j5_user_2 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j5_user_3;
	GRANT       plan_3_years TO j5_user_3;
	ALTER ROLE  j5_user_3 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j5_user_4;
	GRANT       plan_5_years TO j5_user_4;
	ALTER ROLE  j5_user_4 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j5_user_5;
	GRANT       j35 TO j5_user_5;
	ALTER ROLE  j5_user_5 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j5_user_6;
	GRANT       j35 TO j5_user_6;
	ALTER ROLE  j5_user_6 WITH LOGIN PASSWORD 'user_2';
	CREATE ROLE j6_chief;
	GRANT       j6 TO j6_chief;
	ALTER ROLE  j6_chief WITH LOGIN PASSWORD 'user_chief_j6';
	CREATE ROLE j6_user_1;
	GRANT       helpdesk TO j6_user_1;
	ALTER ROLE  j6_user_1 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j6_user_2;
	GRANT       doc_rules TO j6_user_2;
	ALTER ROLE  j6_user_2 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j6_user_3;
	GRANT       doc_rules TO j6_user_3;
	ALTER ROLE  j6_user_3 WITH LOGIN PASSWORD 'user_2';
	CREATE ROLE j6_user_4;
	GRANT       com_plan TO j6_user_4;
	ALTER ROLE  j6_user_4 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j6_user_5;
	GRANT       post_office TO j6_user_5;
	ALTER ROLE  j6_user_5 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j6_user_6;
	GRANT       transmission TO j6_user_6;
	ALTER ROLE  j6_user_6 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j7_chief;
	GRANT       j7 TO j7_chief;
	ALTER ROLE  j7_chief WITH LOGIN PASSWORD 'user_chief_j7';
	CREATE ROLE j7_user_1;
	GRANT       plan_ow TO j7_user_1;
	ALTER ROLE  j7_user_1 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j7_user_2;
	GRANT       international_relation TO j7_user_2;
	ALTER ROLE  j7_user_2 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j8_chief;
	GRANT       j8 TO j8_chief;
	ALTER ROLE  j8_chief WITH LOGIN PASSWORD 'user_chief_j8';
	CREATE ROLE j8_user_1;
	GRANT       procurement_office TO j8_user_1;
	ALTER ROLE  j8_user_1 WITH LOGIN PASSWORD 'user_1';
	CREATE ROLE j8_user_3;
	GRANT       plan_ad TO j8_user_3;
	ALTER ROLE  j8_user_3 WITH LOGIN PASSWORD 'user_1';

EOSQL

