#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname pe_1  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA personnel TO promotion;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA personnel TO j1_chief;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA personnel TO employees;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA personnel TO promotion;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA personnel TO employees;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA personnel TO promotion;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA personnel TO employees;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA personnel TO promotion;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA personnel TO employees;
	GRANT ALL ON SCHEMA personnel TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA employees TO promotion;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA employees TO j1_chief;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA employees TO employees;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA employees TO promotion;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA employees TO employees;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA employees TO promotion;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA employees TO employees;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA employees TO promotion;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA employees TO employees;
	GRANT ALL ON SCHEMA employees TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO promotion;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j1_chief;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO employees;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO promotion;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO employees;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO promotion;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO employees;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO promotion;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO employees;
	GRANT ALL ON SCHEMA public TO j1;

EOSQL

