#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname w_1  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA commercial TO welfare;
	GRANT ALL ON SCHEMA commercial TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA commercial TO j1_chief;
	GRANT ALL ON SCHEMA commercial TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA commercial TO welfare;
	GRANT ALL ON SCHEMA commercial TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA commercial TO welfare;
	GRANT ALL ON SCHEMA commercial TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA commercial TO welfare;
	GRANT ALL ON SCHEMA commercial TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA taxes TO welfare;
	GRANT ALL ON SCHEMA taxes TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA taxes TO j1_chief;
	GRANT ALL ON SCHEMA taxes TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA taxes TO welfare;
	GRANT ALL ON SCHEMA taxes TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA taxes TO welfare;
	GRANT ALL ON SCHEMA taxes TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA taxes TO welfare;
	GRANT ALL ON SCHEMA taxes TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO welfare;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j1_chief;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO welfare;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO welfare;
	GRANT ALL ON SCHEMA public TO j1;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO welfare;
	GRANT ALL ON SCHEMA public TO j1;

EOSQL

