#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname ops_1  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA ops_og TO ops;
	GRANT ALL ON SCHEMA ops_og TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA ops_og TO j3_chief;
	GRANT ALL ON SCHEMA ops_og TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA ops_og TO j5_chief;
	GRANT ALL ON SCHEMA ops_og TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA ops_og TO ops;
	GRANT ALL ON SCHEMA ops_og TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA ops_og TO j3_chief;
	GRANT ALL ON SCHEMA ops_og TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA ops_og TO ops;
	GRANT ALL ON SCHEMA ops_og TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA ops_og TO j3_chief;
	GRANT ALL ON SCHEMA ops_og TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA ops_og TO ops;
	GRANT ALL ON SCHEMA ops_og TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA ops_f TO ops;
	GRANT ALL ON SCHEMA ops_f TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA ops_f TO j3_chief;
	GRANT ALL ON SCHEMA ops_f TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA ops_f TO j5_chief;
	GRANT ALL ON SCHEMA ops_f TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA ops_f TO ops;
	GRANT ALL ON SCHEMA ops_f TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA ops_f TO j3_chief;
	GRANT ALL ON SCHEMA ops_f TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA ops_f TO ops;
	GRANT ALL ON SCHEMA ops_f TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA ops_f TO j3_chief;
	GRANT ALL ON SCHEMA ops_f TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA ops_f TO ops;
	GRANT ALL ON SCHEMA ops_f TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO ops;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j3_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j5_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO ops;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO j3_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO ops;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO j3_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO ops;
	GRANT ALL ON SCHEMA public TO j3;

EOSQL

