#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname training  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA trn_q TO training;
	GRANT ALL ON SCHEMA trn_q TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA trn_q TO ops;
	GRANT ALL ON SCHEMA trn_q TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA trn_q TO j3_chief;
	GRANT ALL ON SCHEMA trn_q TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA trn_q TO j5_chief;
	GRANT ALL ON SCHEMA trn_q TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA trn_q TO training;
	GRANT ALL ON SCHEMA trn_q TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA trn_q TO training;
	GRANT ALL ON SCHEMA trn_q TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA trn_q TO training;
	GRANT ALL ON SCHEMA trn_q TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA trn_lt TO training;
	GRANT ALL ON SCHEMA trn_lt TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA trn_lt TO ops;
	GRANT ALL ON SCHEMA trn_lt TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA trn_lt TO j3_chief;
	GRANT ALL ON SCHEMA trn_lt TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA trn_lt TO j5_chief;
	GRANT ALL ON SCHEMA trn_lt TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA trn_lt TO training;
	GRANT ALL ON SCHEMA trn_lt TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA trn_lt TO training;
	GRANT ALL ON SCHEMA trn_lt TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA trn_lt TO training;
	GRANT ALL ON SCHEMA trn_lt TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO training;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO ops;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j3_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j5_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO training;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO training;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO training;
	GRANT ALL ON SCHEMA public TO j3;

EOSQL

