#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname plan_24_1  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_24_r TO plan_24;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_24_r TO ops;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_24_r TO j3_chief;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_24_r TO plan_24;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_24_r TO ops;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_24_r TO j3_chief;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA plan_24_r TO plan_24;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA plan_24_r TO ops;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA plan_24_r TO j3_chief;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA plan_24_r TO plan_24;
	GRANT ALL ON SCHEMA plan_24_r TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_24_f TO plan_24;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_24_f TO ops;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_24_f TO j3_chief;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_24_f TO plan_24;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_24_f TO ops;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_24_f TO j3_chief;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA plan_24_f TO plan_24;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA plan_24_f TO ops;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA plan_24_f TO j3_chief;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA plan_24_f TO plan_24;
	GRANT ALL ON SCHEMA plan_24_f TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO plan_24;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO ops;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j3_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO plan_24;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO ops;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO j3_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO plan_24;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO ops;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO j3_chief;
	GRANT ALL ON SCHEMA public TO j3;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO plan_24;
	GRANT ALL ON SCHEMA public TO j3;

EOSQL

