#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname move_1  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA move_w TO move;
	GRANT ALL ON SCHEMA move_w TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA move_w TO j4_chief;
	GRANT ALL ON SCHEMA move_w TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA move_w TO move;
	GRANT ALL ON SCHEMA move_w TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA move_w TO move;
	GRANT ALL ON SCHEMA move_w TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA move_w TO move;
	GRANT ALL ON SCHEMA move_w TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA move_lt TO move;
	GRANT ALL ON SCHEMA move_lt TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA move_lt TO j4_chief;
	GRANT ALL ON SCHEMA move_lt TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA move_lt TO move;
	GRANT ALL ON SCHEMA move_lt TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA move_lt TO move;
	GRANT ALL ON SCHEMA move_lt TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA move_lt TO move;
	GRANT ALL ON SCHEMA move_lt TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO move;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j4_chief;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO move;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO move;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO move;
	GRANT ALL ON SCHEMA public TO j4;

EOSQL

