#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname maint_1  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA maint_w TO maint;
	GRANT ALL ON SCHEMA maint_w TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA maint_w TO j4_chief;
	GRANT ALL ON SCHEMA maint_w TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA maint_w TO maint;
	GRANT ALL ON SCHEMA maint_w TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA maint_w TO maint;
	GRANT ALL ON SCHEMA maint_w TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA maint_w TO maint;
	GRANT ALL ON SCHEMA maint_w TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA maint_d TO maint;
	GRANT ALL ON SCHEMA maint_d TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA maint_d TO j4_chief;
	GRANT ALL ON SCHEMA maint_d TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA maint_d TO maint;
	GRANT ALL ON SCHEMA maint_d TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA maint_d TO maint;
	GRANT ALL ON SCHEMA maint_d TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA maint_d TO maint;
	GRANT ALL ON SCHEMA maint_d TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO maint;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j4_chief;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO maint;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO maint;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO maint;
	GRANT ALL ON SCHEMA public TO j4;

EOSQL

