#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname supply_1  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA supply_w TO supply;
	GRANT ALL ON SCHEMA supply_w TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA supply_w TO j4_chief;
	GRANT ALL ON SCHEMA supply_w TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA supply_w TO supply;
	GRANT ALL ON SCHEMA supply_w TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA supply_w TO supply;
	GRANT ALL ON SCHEMA supply_w TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA supply_w TO supply;
	GRANT ALL ON SCHEMA supply_w TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA supply_lt TO supply;
	GRANT ALL ON SCHEMA supply_lt TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA supply_lt TO j4_chief;
	GRANT ALL ON SCHEMA supply_lt TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA supply_lt TO supply;
	GRANT ALL ON SCHEMA supply_lt TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA supply_lt TO supply;
	GRANT ALL ON SCHEMA supply_lt TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA supply_lt TO supply;
	GRANT ALL ON SCHEMA supply_lt TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO supply;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j4_chief;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO supply;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO supply;
	GRANT ALL ON SCHEMA public TO j4;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO supply;
	GRANT ALL ON SCHEMA public TO j4;

EOSQL

