#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname plan_ad_1  <<-EOSQL
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_ad_s TO plan_ad;
	GRANT ALL ON SCHEMA plan_ad_s TO j8;
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_ad_s TO j8_chief;
	GRANT ALL ON SCHEMA plan_ad_s TO j8;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_ad_s TO plan_ad;
	GRANT ALL ON SCHEMA plan_ad_s TO j8;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_ad_s TO j8_chief;
	GRANT ALL ON SCHEMA plan_ad_s TO j8;
	GRANT UPDATE ON ALL TABLES IN SCHEMA plan_ad_s TO plan_ad;
	GRANT ALL ON SCHEMA plan_ad_s TO j8;
	GRANT DELETE ON ALL TABLES IN SCHEMA plan_ad_s TO plan_ad;
	GRANT ALL ON SCHEMA plan_ad_s TO j8;
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_ad_b TO plan_ad;
	GRANT ALL ON SCHEMA plan_ad_b TO j8;
	GRANT SELECT ON ALL TABLES IN SCHEMA plan_ad_b TO j8_chief;
	GRANT ALL ON SCHEMA plan_ad_b TO j8;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_ad_b TO plan_ad;
	GRANT ALL ON SCHEMA plan_ad_b TO j8;
	GRANT INSERT ON ALL TABLES IN SCHEMA plan_ad_b TO j8_chief;
	GRANT ALL ON SCHEMA plan_ad_b TO j8;
	GRANT UPDATE ON ALL TABLES IN SCHEMA plan_ad_b TO plan_ad;
	GRANT ALL ON SCHEMA plan_ad_b TO j8;
	GRANT DELETE ON ALL TABLES IN SCHEMA plan_ad_b TO plan_ad;
	GRANT ALL ON SCHEMA plan_ad_b TO j8;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO plan_ad;
	GRANT ALL ON SCHEMA public TO j8;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO j8_chief;
	GRANT ALL ON SCHEMA public TO j8;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO plan_ad;
	GRANT ALL ON SCHEMA public TO j8;
	GRANT INSERT ON ALL TABLES IN SCHEMA public TO j8_chief;
	GRANT ALL ON SCHEMA public TO j8;
	GRANT UPDATE ON ALL TABLES IN SCHEMA public TO plan_ad;
	GRANT ALL ON SCHEMA public TO j8;
	GRANT DELETE ON ALL TABLES IN SCHEMA public TO plan_ad;
	GRANT ALL ON SCHEMA public TO j8;

EOSQL

